title: Diego Kiedanski
description: "ML Engineer @ Tryolabs | Ph.D from I.P. Paris"
theme: jekyll-theme-minimal
logo: "assets/img/snowme.jpg"
personal:
  linkedin: "https://linkedin.com/in/diego-kiedanski"
  github: "https://github.com/gus0k"
  googlescholar: "https://scholar.google.com/citations?user=L1Qe4zgAAAAJ&hl=en"
